version: "3.9"

services:
  mypostgres:
    image: postgres:13
    container_name: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: toyotadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    container_name: productService
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres:5432/toyotadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - mypostgres

  user-service:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    container_name: userService
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres:5432/toyotadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - mypostgres

  report-service:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    container_name: reportService
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres:5432/toyotadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - mypostgres

  sale-service:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    container_name: saleService
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres:5432/toyotadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - mypostgres

  verification-authorization-service:
    build:
      context: ./backendproject
      dockerfile: Dockerfile
    container_name: verificationAuthorizationService
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres:5432/toyotadb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - mypostgres

volumes:
  postgres_data:
